### PR TITLE
[v0.6] Queues & Caches

### LINKED ISSUE #40: Title and meta tags don't updated
Hi, how can i make html head updated for each page when i use ajax request in links

### PR DESCRIPTION
**Pull request by imacrayon**
This PR introduces a new request queuing and caching system that will support client-side routing features similar to `hx-boost` and Hotwire's Turbo.

The queue will handle concurrency issues in situations where multiple requests could cause race conditions, like when a user is clicking faster than the server can respond, or multiple AJAX requests target the same element on the page.

The cache will store AJAX responses in memory and reuse the response on subsequent requests before requesting fresh data. The user will experience instant UI changes as they navigate between pages that have been cached.

I'd also like to introduce support for pre-fetching requests to make page navigation feel even faster.

~~I also rewrote Alpine AJAX using a class-based architecture, concepts are better organized now, and the code base is a few kBs smaller when compressed.~~ _The project ended up growing considerably in size, so I reverted a lot of these changes._

So far I don't see any new APIs required to make this all work. My plan is that it will all just be automatically available after installing Alpine AJAX.

Fixes #40

### CODE REVIEW

**Comment by imacrayon** [comment]
Alright, all tests except for the redirect tests are passing now. Redirects will need to be handled a little differently now because full page reloads no longer exist. I still have a few bigger concerns to work through before I feel good about adding this features:
1. Alpine AJAX caches previous requests. When making a new request, if a cached request exists, Alpine AJAX will immediately render the cached request before issuing a request for fresh content. Once fresh content is received the new content is then rendered. This makes page navigation feel super fast, but every request for content essentially triggers two rendering passes. I'm worried that on slow networks these two renders could produce a jarring experience as the UI swaps between stale and fresh content.
2. Navigating to a page you've already visited now feels almost instant, however every request to a **new** page is slightly slower than a standard full page refresh. This is because Alpine AJAX has to spend extra cycles rendering content and merging `<head>` element between page requests. After some testing I've found these same issue to be true for most other client side navigation libraries (Turbo, HTMX, Unpoly, Livewire), but I'm not convinced that this tradeoff is really worth it for users. I want to look into ways Alpine AJAX might be able to work around these trade offs using a Service Worker. We might be able to offload some of the extra rendering work to the browser (fast) instead of JavaScript (slow).

**Comment by saolof** [comment]
I just want to mention that I am incredibly impressed by how everything just beautifully falls out of the basic rules of this library!

**Comment by davekaro** [comment]
> however every request to a new page is slightly slower than a standard full page refresh
...
> After some testing I've found these same issue to be true for most other client side navigation libraries (Turbo, HTMX, Unpoly, Livewire)

Can you describe how you tested this? I've been using the Chrome dev tools performance tab and hit record, navigate to a page, hit stop, then comparing the reported Scripting/Rendering/Painting times. There was some discussion on the benefits (or not) of Turbo Drive a while back (see https://x.com/fxn/status/1759533608044249440, though most of responses have been deleted), and I think the conclusion drawn was that by using Turbo Drive, you potentially save on the execution time of browser extensions because they tend to run on load of each page, whereas using Turbo Drive that only happens on initial load. For myself, I remain skeptical of the benefits, especially since with no extensions it is faster to do regular full page navigation.

Also, since the addition of the documentation on Navigation (https://alpine-ajax.js.org/reference/#navigation, added in https://github.com/imacrayon/alpine-ajax/commit/53f101f1882727e45ff8ff49eea8181cd0955f1b long after this PR was created), are you still thinking of adding these features? The documentation seems to argue against it.

**Comment by imacrayon** [comment]
Hey @davekaro, thanks for reminding me that there's some loose ends to tie up here.

To answer your question about testing Turbo Drive: I installed Turbo on a local copy of the Alpine AJAX documentation site. On every page of the site I included this markup just before the end of the `<body>`: `<script>console.log(Date.now())</script>`. Finally, I logged a timestamp on every link click. These are some results measuring the time in milliseconds between the moment a link was clicked and the moment the `<script>` tag at the bottom of the page fired:

```
Navigating from the Homepage to the Reference page:

Browser:
2658
2660
2665
2672
2664
---
Average: 2663.8

Turbo Drive (Turbo Drive when cached)
2728 (52)
2715 (58)
2703 (57)
2699 (56)
2697 (54)
---
Average: 2708 (55.4)

Livewire Navigate
2685
2697
2682
2681
2714
---
Average: 2691.8
```

You'll notice that the first time a user navigates to a page, Turbo and Livewire are slightly slower than the standard browser navigation, however after a page has been cached, Turbo is significantly faster on subsequent visits.

Similar to that tweet you mentioned, my take away is that while Turbo does provide performance benefits on return visits to the same page, those benefits aren't worth the extra code complexity. Keep in mind that Turbo flushes it's cache after form submissions and when users close the browser tab, so that also reduces the likelihood that a page you've already visited exists in Turbo's cache.

**Comment by imacrayon** [comment]
I'm closing this PR for now, there's a [Navigation section that was recently added to the documentation](https://alpine-ajax.js.org/reference/#navigation) which explains my current thinking on SPA-style navigation.

**Pull request closed without merging**
